#!/usr/bin/env python3
"""Validate skills, pack manifests, and committed pack zips.

Checks:
1. Every skills/<name>/SKILL.md has YAML frontmatter with a `name` that is
   lowercase-hyphen and matches its folder, and a `description` <= 1024 chars.
2. Every packs/<persona>.json parses and only references skills that exist.
3. Committed packs/*-pack.zip match a fresh build (content compare with
   normalized line endings, so zip timestamps and CRLF do not false-positive).

Exit code 0 = all good; 1 = validation failure. Run by CI on every push/PR.
"""

import hashlib
import json
import re
import subprocess
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).parent.parent
SKILLS_DIR = ROOT / "skills"
PACKS_DIR = ROOT / "packs"
DIST_DIR = ROOT / "dist"

NAME_RE = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*$")

errors: list[str] = []


def err(msg: str) -> None:
    errors.append(msg)
    print(f"  [FAIL] {msg}")


def validate_skills() -> None:
    print("Validating SKILL.md frontmatter...")
    for skill_dir in sorted(SKILLS_DIR.iterdir()):
        if not skill_dir.is_dir():
            continue
        skill_file = skill_dir / "SKILL.md"
        if not skill_file.exists():
            err(f"{skill_dir.name}: missing SKILL.md")
            continue
        content = skill_file.read_text(encoding="utf-8")
        match = re.match(r"^---\n(.*?)\n---", content, re.DOTALL)
        if not match:
            err(f"{skill_dir.name}: no YAML frontmatter")
            continue
        fm = match.group(1)
        # Strict YAML parse when PyYAML is available: unquoted colons in
        # description break strict parsers (e.g. Claude.ai uploads) even
        # though the regex checks below still pass.
        try:
            import yaml  # type: ignore

            try:
                yaml.safe_load(fm)
            except yaml.YAMLError as exc:
                err(f"{skill_dir.name}: frontmatter is not strict YAML ({exc})")
        except ImportError:
            pass
        name_match = re.search(r"^name:\s*(.+)$", fm, re.MULTILINE)
        if not name_match:
            err(f"{skill_dir.name}: frontmatter missing `name`")
        else:
            name = name_match.group(1).strip()
            if name != skill_dir.name:
                err(f"{skill_dir.name}: frontmatter name `{name}` != folder name")
            if not NAME_RE.match(name):
                err(f"{skill_dir.name}: name `{name}` is not lowercase-hyphen")
            if len(name) > 64:
                err(f"{skill_dir.name}: name exceeds 64 chars")
        desc_match = re.search(
            r"^description:\s*(.+?)(?=^\w+:|\Z)", fm, re.DOTALL | re.MULTILINE
        )
        if not desc_match:
            err(f"{skill_dir.name}: frontmatter missing `description`")
        else:
            desc = re.sub(r"\s+", " ", desc_match.group(1)).strip()
            if len(desc) > 1024:
                err(f"{skill_dir.name}: description exceeds 1024 chars ({len(desc)})")
            if len(desc) < 40:
                err(f"{skill_dir.name}: description suspiciously short ({len(desc)} chars)")


def validate_manifests() -> None:
    print("Validating pack manifests...")
    skill_names = {d.name for d in SKILLS_DIR.iterdir() if d.is_dir()}
    for manifest_path in sorted(PACKS_DIR.glob("*.json")):
        try:
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as e:
            err(f"{manifest_path.name}: invalid JSON - {e}")
            continue
        for entry in manifest.get("skills", []):
            if entry.get("name") not in skill_names:
                err(f"{manifest_path.name}: unknown skill `{entry.get('name')}`")
        for recipe in manifest.get("recipes", []):
            for composed in recipe.get("composes", []):
                if composed not in skill_names:
                    err(
                        f"{manifest_path.name}: recipe `{recipe.get('name')}` "
                        f"composes unknown skill `{composed}`"
                    )
        for ref in manifest.get("references", []):
            src = ref.get("src", "")
            # recipes.md is generated by the build script; all others must exist
            if src != "references/recipes.md" and not (ROOT / src).exists():
                err(f"{manifest_path.name}: reference `{src}` does not exist")


def _zip_content_map(path: Path) -> dict:
    zf = zipfile.ZipFile(path)
    return {
        n: hashlib.md5(zf.read(n).replace(b"\r\n", b"\n")).hexdigest()
        for n in zf.namelist()
        if not n.endswith("/")
    }


def validate_zip_freshness() -> None:
    print("Rebuilding packs and comparing against committed zips...")
    result = subprocess.run(
        [sys.executable, str(ROOT / "scripts" / "build-packs.py"), "--no-publish"],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        err(f"build-packs.py failed:\n{result.stdout}\n{result.stderr}")
        return
    committed_zips = sorted(PACKS_DIR.glob("*-pack.zip")) + sorted(
        (PACKS_DIR / "skills").glob("*.zip")
    )
    fresh_by_name = {z.name: z for z in DIST_DIR.glob("*.zip")}
    fresh_by_name.update({z.name: z for z in (DIST_DIR / "skills").glob("*.zip")})
    fresh_skill_zips = {z.name for z in (DIST_DIR / "skills").glob("*.zip")}
    committed_skill_zips = {z.name for z in (PACKS_DIR / "skills").glob("*.zip")}
    for missing in sorted(fresh_skill_zips - committed_skill_zips):
        err(
            f"packs/skills/{missing} is missing but the build produces it. "
            f"Run `python scripts/build-packs.py` and commit."
        )
    for orphan in sorted(committed_skill_zips - fresh_skill_zips):
        err(f"packs/skills/{orphan} has no corresponding skill in skills/. Delete it.")
    for committed in committed_zips:
        fresh = fresh_by_name.get(committed.name)
        if fresh is None or not fresh.exists():
            err(f"{committed.name}: build did not produce this pack")
            continue
        old, new = _zip_content_map(committed), _zip_content_map(fresh)
        removed = sorted(set(old) - set(new))
        added = sorted(set(new) - set(old))
        changed = sorted(n for n in set(old) & set(new) if old[n] != new[n])
        if removed or added or changed:
            detail = "; ".join(
                filter(
                    None,
                    [
                        f"removed: {removed}" if removed else "",
                        f"added: {added}" if added else "",
                        f"changed: {changed}" if changed else "",
                    ],
                )
            )
            err(
                f"{committed.name} is STALE vs source ({detail}). "
                f"Run `python scripts/build-packs.py` and commit the refreshed zips."
            )


def main() -> None:
    validate_skills()
    validate_manifests()
    validate_zip_freshness()
    print("=" * 40)
    if errors:
        print(f"FAILED: {len(errors)} validation error(s)")
        sys.exit(1)
    print("All validations passed.")


if __name__ == "__main__":
    main()
